var webapproot = "/eCONTRACT";
var ozserverUrl = location.protocol + "//" + location.hostname +(location.port ? ':'+location.port: '') + webapproot;
var ozbaseparam = "connection.servlet=" + ozserverUrl + "/server";
var reportname = "local://localrepository/A.ozd";
var odiparams = "";
var formparams = "";
var childreportnames = "";
var bindinputreport = new Array();

/*ozviewer basic param */
var p_oz = new Array();
p_oz[p_oz.length] = "global.concatpage=true";
p_oz[p_oz.length] = "global.inheritparameter=true";
p_oz[p_oz.length] = "global.language=en/US";
p_oz[p_oz.length] = "information.debug=true";
p_oz[p_oz.length] = "comment.all=true";
p_oz[p_oz.length] = "comment.autohide=false";      
p_oz[p_oz.length] = "comment.sizebuttons=true";
p_oz[p_oz.length] = "comment.colorbuttons=true";
p_oz[p_oz.length] = "comment.selectedpen=hightlightpen";
p_oz[p_oz.length] = "comment.pen_thick=2";
p_oz[p_oz.length] = "comment.pen_color=FF0000";
p_oz[p_oz.length] = "comment.highlightpen_thick=10";
p_oz[p_oz.length] = "comment.highlightpen_color=FF0000";
p_oz[p_oz.length] = "comment.hideatinputmode=true";
p_oz[p_oz.length] = "comment.confirmclear=true";
p_oz[p_oz.length] = "viewer.focus_doc_index=0";
p_oz[p_oz.length] = "viewer.showtree=true";
p_oz[p_oz.length] = "viewer.progresscommand=true";
p_oz[p_oz.length] = "viewer.exportcommand=true";
p_oz[p_oz.length] = "viewer.useractioncommand=true";
p_oz[p_oz.length] = "viewer.ignore_disable_color_inputcomponent=true";
p_oz[p_oz.length] = "viewer.bgcolor=ffffff";
p_oz[p_oz.length] = "viewer.ignore_disable_color_inputcomponent=true";
p_oz[p_oz.length] = "viewer.usestatusbar=false";
p_oz[p_oz.length] = "viewer.zoombymouse=false";
p_oz[p_oz.length] = "eform.signpad_type=zoom";
p_oz[p_oz.length] = "eform.show_prev_next_input=true";
p_oz[p_oz.length] = "eform.functionbutton_display_type=showpreviewonly";
p_oz[p_oz.length] = "toolbar.all=true";
p_oz[p_oz.length] = "toolbar.save=false";
p_oz[p_oz.length] = "toolbar.savedm=false";
p_oz[p_oz.length] = "connection.compresseddatamodule=true";
p_oz[p_oz.length] = "connection.compressedForm=true";
p_oz[p_oz.length] = "connection.datafromserver=false";