
package mn.unitel.websvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Ucbs", targetNamespace = "http://websvc.unitel.mn", wsdlLocation = "https://www.unitel.mn/ucbs.php/unitel/services/Ucbs?wsdl")
public class Ucbs
    extends Service
{

    private final static URL UCBS_WSDL_LOCATION;
    private final static WebServiceException UCBS_EXCEPTION;
    private final static QName UCBS_QNAME = new QName("http://websvc.unitel.mn", "Ucbs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.unitel.mn/ucbs.php/unitel/services/Ucbs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UCBS_WSDL_LOCATION = url;
        UCBS_EXCEPTION = e;
    }

    public Ucbs() {
        super(__getWsdlLocation(), UCBS_QNAME);
    }

    public Ucbs(WebServiceFeature... features) {
        super(__getWsdlLocation(), UCBS_QNAME, features);
    }

    public Ucbs(URL wsdlLocation) {
        super(wsdlLocation, UCBS_QNAME);
    }

    public Ucbs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UCBS_QNAME, features);
    }

    public Ucbs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ucbs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UcbsPortType
     */
    @WebEndpoint(name = "UcbsHttpSoap11Endpoint")
    public UcbsPortType getUcbsHttpSoap11Endpoint() {
        return super.getPort(new QName("http://websvc.unitel.mn", "UcbsHttpSoap11Endpoint"), UcbsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UcbsPortType
     */
    @WebEndpoint(name = "UcbsHttpSoap11Endpoint")
    public UcbsPortType getUcbsHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://websvc.unitel.mn", "UcbsHttpSoap11Endpoint"), UcbsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UCBS_EXCEPTION!= null) {
            throw UCBS_EXCEPTION;
        }
        return UCBS_WSDL_LOCATION;
    }

}
