
package mn.unitel.websvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mn.unitel.websvc.ucbs.xsd.ContractRequest;
import mn.unitel.websvc.ucbs.xsd.LoginResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UcbsPortType", targetNamespace = "http://websvc.unitel.mn")
@XmlSeeAlso({
    mn.unitel.websvc.ObjectFactory.class,
    mn.unitel.websvc.ucbs.xsd.ObjectFactory.class
})
public interface UcbsPortType {


    /**
     * 
     * @param id
     * @param contractid
     * @param auth
     * @return
     *     returns mn.unitel.websvc.ucbs.xsd.ContractRequest
     */
    @WebMethod(action = "urn:onlinecontract")
    @WebResult(targetNamespace = "http://websvc.unitel.mn")
    @RequestWrapper(localName = "onlinecontract", targetNamespace = "http://websvc.unitel.mn", className = "mn.unitel.websvc.Onlinecontract")
    @ResponseWrapper(localName = "onlinecontractResponse", targetNamespace = "http://websvc.unitel.mn", className = "mn.unitel.websvc.OnlinecontractResponse")
    public ContractRequest onlinecontract(
        @WebParam(name = "auth", targetNamespace = "http://websvc.unitel.mn")
        String auth,
        @WebParam(name = "id", targetNamespace = "http://websvc.unitel.mn")
        Integer id,
        @WebParam(name = "contractid", targetNamespace = "http://websvc.unitel.mn")
        String contractid);

    /**
     * 
     * @param id
     * @param user
     * @param auth
     * @param pass
     * @return
     *     returns mn.unitel.websvc.ucbs.xsd.LoginResult
     */
    @WebMethod(action = "urn:login")
    @WebResult(targetNamespace = "http://websvc.unitel.mn")
    @RequestWrapper(localName = "login", targetNamespace = "http://websvc.unitel.mn", className = "mn.unitel.websvc.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://websvc.unitel.mn", className = "mn.unitel.websvc.LoginResponse")
    public LoginResult login(
        @WebParam(name = "auth", targetNamespace = "http://websvc.unitel.mn")
        String auth,
        @WebParam(name = "id", targetNamespace = "http://websvc.unitel.mn")
        Integer id,
        @WebParam(name = "user", targetNamespace = "http://websvc.unitel.mn")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://websvc.unitel.mn")
        String pass);

    /**
     * 
     * @param id
     * @param prodNo
     * @param contractType
     * @param auth
     * @return
     *     returns mn.unitel.websvc.ucbs.xsd.ContractRequest
     */
    @WebMethod(operationName = "onlinecontract_new", action = "urn:onlinecontract_new")
    @WebResult(targetNamespace = "http://websvc.unitel.mn")
    @RequestWrapper(localName = "onlinecontract_new", targetNamespace = "http://websvc.unitel.mn", className = "mn.unitel.websvc.OnlinecontractNew")
    @ResponseWrapper(localName = "onlinecontract_newResponse", targetNamespace = "http://websvc.unitel.mn", className = "mn.unitel.websvc.OnlinecontractNewResponse")
    public ContractRequest onlinecontractNew(
        @WebParam(name = "auth", targetNamespace = "http://websvc.unitel.mn")
        String auth,
        @WebParam(name = "id", targetNamespace = "http://websvc.unitel.mn")
        Integer id,
        @WebParam(name = "prod_no", targetNamespace = "http://websvc.unitel.mn")
        String prodNo,
        @WebParam(name = "contractType", targetNamespace = "http://websvc.unitel.mn")
        String contractType);

}
